language: node_js
node_js:
  - '12'
branches:
  only:
    - master
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - mkdir -p Wiki
  - rsync -av ./ ./Wiki --exclude=docusaurus --remove-source-files
  - mv ./docusaurus/* .
  - yarn
  - GIT_USER="${GH_NAME}" yarn deploy
  - popd
