language: node_js
node_js:
  - '12'
branches:
  only:
    - master
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - mkdir -p Wiki
  - rsync -a ./ ./Wiki --exclude=docusaurus,.git --remove-source-files
  - ls -la Wiki
  - ls -la docusaurus
  - cp -vR ./docusaurus/* .
  - ls -la
  - yarn
  - ls -la
  - GIT_USER="${GH_NAME}" yarn deploy
