language: node_js
node_js:
  - '12'
branches:
  only:
    - master
    - j2d
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - export GIT_USER="${GH_NAME}"
  - ./scripts/deploy.sh
