version: "3.5"
services:
  docusaurus:
    image: node:16-alpine
    working_dir: /app
    command: ["/bin/sh", "/app/wiki/scripts/develop.sh"]
    volumes:
      - ./docusaurus:/app
      - ./:/app/wiki
      - ./Assets:/app/static/Assets
      - ./raw-attachment:/app/static/raw-attachment
      - empty:/app/wiki/docusaurus
    ports:
      - 3000:3000
volumes:
  empty:
