name: Manual deploy wiki
on: workflow_dispatch

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn
        cache-dependency-path: docusaurus/yarn.lock
    - name: Build
      run: ./scripts/build.sh
    - name: Cache build wiki assets
      uses: actions/cache@v2
      with:
        path: |
          docusaurus/wiki
          docusaurus/static/Assets
          docusaurus/static
