name: Manual deploy wiki
on: workflow_dispatch

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn
        cache-dependency-path: docusaurus/yarn.lock
    - name: Build
      run: ./scripts/build.sh
    - name: Cache build wiki assets
      uses: actions/cache@v3
      with:
        path: |
          docusaurus/wiki
          docusaurus/static/Assets
          docusaurus/static/raw-attachment
        key: ${{ runner.os }}-assets

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Build output to publish to the `gh-pages` branch:
        publish_dir: ./build
        # The following lines assign commit authorship to the official
        # GH-Actions bot for deploys to `gh-pages` branch:
        # https://github.com/actions/checkout/issues/13#issuecomment-724415212
        # The GH actions bot is used by default if you didn't specify the two fields.
        # You can swap them out with your own user credentials.
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
