name: Manual deploy wiki
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 12.x
    - run: yarn
    - run: yarn build
